FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Day03/Day03.csproj", "Day03/"]
RUN dotnet restore "Day03/Day03.csproj"
COPY . .
WORKDIR "/src/Day03"
RUN dotnet build "Day03.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Day03.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Day03.dll"]
